# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/build/CMakeFiles /app/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_example

# Build rule for target.
opencv_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_example
.PHONY : opencv_example

# fast build rule for target.
opencv_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/build
.PHONY : opencv_example/fast

#=============================================================================
# Target rules for targets named liblccv

# Build rule for target.
liblccv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 liblccv
.PHONY : liblccv

# fast build rule for target.
liblccv/fast:
	$(MAKE) $(MAKESILENT) -f lib/LCCV/CMakeFiles/liblccv.dir/build.make lib/LCCV/CMakeFiles/liblccv.dir/build
.PHONY : liblccv/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nano.o: src/nano.cpp.o
.PHONY : src/nano.o

# target to build an object file
src/nano.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/nano.cpp.o
.PHONY : src/nano.cpp.o

src/nano.i: src/nano.cpp.i
.PHONY : src/nano.i

# target to preprocess a source file
src/nano.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/nano.cpp.i
.PHONY : src/nano.cpp.i

src/nano.s: src/nano.cpp.s
.PHONY : src/nano.s

# target to generate assembly for a file
src/nano.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/nano.cpp.s
.PHONY : src/nano.cpp.s

src/tracker.o: src/tracker.cpp.o
.PHONY : src/tracker.o

# target to build an object file
src/tracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker.cpp.o
.PHONY : src/tracker.cpp.o

src/tracker.i: src/tracker.cpp.i
.PHONY : src/tracker.i

# target to preprocess a source file
src/tracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker.cpp.i
.PHONY : src/tracker.cpp.i

src/tracker.s: src/tracker.cpp.s
.PHONY : src/tracker.s

# target to generate assembly for a file
src/tracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker.cpp.s
.PHONY : src/tracker.cpp.s

src/tracker_runner.o: src/tracker_runner.cpp.o
.PHONY : src/tracker_runner.o

# target to build an object file
src/tracker_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker_runner.cpp.o
.PHONY : src/tracker_runner.cpp.o

src/tracker_runner.i: src/tracker_runner.cpp.i
.PHONY : src/tracker_runner.i

# target to preprocess a source file
src/tracker_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker_runner.cpp.i
.PHONY : src/tracker_runner.cpp.i

src/tracker_runner.s: src/tracker_runner.cpp.s
.PHONY : src/tracker_runner.s

# target to generate assembly for a file
src/tracker_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_example.dir/build.make CMakeFiles/opencv_example.dir/src/tracker_runner.cpp.s
.PHONY : src/tracker_runner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... liblccv"
	@echo "... opencv_example"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nano.o"
	@echo "... src/nano.i"
	@echo "... src/nano.s"
	@echo "... src/tracker.o"
	@echo "... src/tracker.i"
	@echo "... src/tracker.s"
	@echo "... src/tracker_runner.o"
	@echo "... src/tracker_runner.i"
	@echo "... src/tracker_runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

